/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("zlh_c_skill_categoryObjectPageObjectPage journey");

        opaTest("Navigate to zlh_c_skill_categoryObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onThezlh_c_skill_categoryListGenerated.onFilterBar().iExecuteSearch();
            Then.onThezlh_c_skill_categoryListGenerated.onTable().iCheckRows();
            When.onThezlh_c_skill_categoryListGenerated.onTable().iPressRow(0);

            Then.onThezlh_c_skill_categoryObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThezlh_c_skill_categoryObjectPageGenerated.iCheckSection({ section: "Category" });
            Then.onThezlh_c_skill_categoryObjectPageGenerated.onForm({ section: "Category" }).iCheckField({ property: "CategoryKey" });
            Then.onThezlh_c_skill_categoryObjectPageGenerated.onForm({ section: "Category" }).iCheckField({ property: "Name" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});