/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("zlh_c_my_course_materialsObjectPageObjectPage journey");

        opaTest("Navigate to zlh_c_my_course_materialsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onThezlh_c_my_coursesListGenerated.onFilterBar().iExecuteSearch();
            Then.onThezlh_c_my_coursesListGenerated.onTable().iCheckRows();
            When.onThezlh_c_my_coursesListGenerated.onTable().iPressRow(0);

            Then.onThezlh_c_my_coursesObjectPageGenerated.iSeeThisPage();
            Then.onThezlh_c_my_coursesObjectPageGenerated.onTable({ property: "_materials" }).iCheckRows();
            When.onThezlh_c_my_coursesObjectPageGenerated.onTable({ property: "_materials" }).iPressRow(0);

            Then.onThezlh_c_my_course_materialsObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            // Ensure the opened entity is not in Draft state before uncommenting
            // Then.onThezlh_c_my_course_materialsObjectPageGenerated.onHeader().iCheckEdit({ visible: true });
            // When.onThezlh_c_my_course_materialsObjectPageGenerated.onHeader().iPressEdit();
            Then.onThezlh_c_my_course_materialsObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.zlh_personal_growth.v0001", action: "markAsFinished", unbound: false } /* , { enabled: true } */);
            // When.onThezlh_c_my_course_materialsObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.zlh_personal_growth.v0001", action: "markAsFinished", unbound: false });
        });

        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onThezlh_c_my_course_materialsObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "Header" });
            Then.onThezlh_c_my_course_materialsObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "MaterialInfo",
                field: "Materialid",
                targetAnnotation: ""
            });
            Then.onThezlh_c_my_course_materialsObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "MaterialInfo",
                field: "CourseId",
                targetAnnotation: ""
            });
            Then.onThezlh_c_my_course_materialsObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "MaterialInfo",
                field: "Name",
                targetAnnotation: ""
            });
            Then.onThezlh_c_my_course_materialsObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "MaterialInfo",
                field: "Duration",
                targetAnnotation: ""
            });
            Then.onThezlh_c_my_course_materialsObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "MaterialInfo",
                field: "Status",
                targetAnnotation: ""
            });
            Then.onThezlh_c_my_course_materialsObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "MaterialInfo",
                field: "Content",
                targetAnnotation: ""
            });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThezlh_c_my_course_materialsObjectPageGenerated.iCheckSection({ section: "Change" });
            Then.onThezlh_c_my_course_materialsObjectPageGenerated.onForm({ section: "Change" }).iCheckField({ property: "Status" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});