/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("zlh_c_my_coursesObjectPageObjectPage journey");

        opaTest("Navigate to zlh_c_my_coursesObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onThezlh_c_my_coursesListGenerated.onFilterBar().iExecuteSearch();
            Then.onThezlh_c_my_coursesListGenerated.onTable().iCheckRows();
            When.onThezlh_c_my_coursesListGenerated.onTable().iPressRow(0);

            Then.onThezlh_c_my_coursesObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            Then.onThezlh_c_my_coursesObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.zlh_personal_growth.v0001", action: "submitRating", unbound: false } /* , { enabled: true } */);
            // When.onThezlh_c_my_coursesObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.zlh_personal_growth.v0001", action: "submitRating", unbound: false });
            Then.onThezlh_c_my_coursesObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.zlh_personal_growth.v0001", action: "sendEmailToModerator", unbound: false }, { enabled: false });
            // When.onThezlh_c_my_coursesObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.zlh_personal_growth.v0001", action: "sendEmailToModerator", unbound: false });
        });

        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onThezlh_c_my_coursesObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "HeaderContainer" });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThezlh_c_my_coursesObjectPageGenerated.iCheckSection({ section: "BookingData" });
            Then.onThezlh_c_my_coursesObjectPageGenerated.onTable({ property: "_materials" }).iCheckAction({ service: "com.sap.gateway.srvd.zlh_personal_growth.v0001", action: "changeStatusMaterial", unbound: false } /* , { enabled: true } */);
            // When.onThezlh_c_my_coursesObjectPageGenerated.onTable({ property: "_materials" }).iPressAction({ service: "com.sap.gateway.srvd.zlh_personal_growth.v0001", action: "changeStatusMaterial", unbound: false });
            Then.onThezlh_c_my_coursesObjectPageGenerated.onTable({ property: "_materials" }).iCheckAction({ service: "com.sap.gateway.srvd.zlh_personal_growth.v0001", action: "markAsFinished", unbound: false } /* , { enabled: true } */);
            // When.onThezlh_c_my_coursesObjectPageGenerated.onTable({ property: "_materials" }).iPressAction({ service: "com.sap.gateway.srvd.zlh_personal_growth.v0001", action: "markAsFinished", unbound: false });
            Then.onThezlh_c_my_coursesObjectPageGenerated.onTable({ property: "_materials" }).iCheckColumns(undefined, {"Materialid":{"header":"UUID"},"CourseId":{"header":"UUID"},"Name":{"header":"Material Name"},"Duration":{"header":"Duration"},"Status":{"header":"Status"},"Content":{"header":"Content"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});