/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("zlh_c_skillObjectPageObjectPage journey");

        opaTest("Navigate to zlh_c_skillObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onThezlh_c_skillListGenerated.onFilterBar().iExecuteSearch();
            Then.onThezlh_c_skillListGenerated.onTable().iCheckRows();
            When.onThezlh_c_skillListGenerated.onTable().iPressRow(0);

            Then.onThezlh_c_skillObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThezlh_c_skillObjectPageGenerated.iCheckSection({ section: "SkillInfo" });
            Then.onThezlh_c_skillObjectPageGenerated.onForm({ section: "SkillInfo" }).iCheckField({ property: "Name" });
            Then.onThezlh_c_skillObjectPageGenerated.onForm({ section: "SkillInfo" }).iCheckField({ property: "Description" });
            Then.onThezlh_c_skillObjectPageGenerated.onForm({ section: "SkillInfo" }).iCheckField({ property: "Category" });
            Then.onThezlh_c_skillObjectPageGenerated.onForm({ section: "SkillInfo" }).iCheckField({ property: "AquiredByMe" });
            Then.onThezlh_c_skillObjectPageGenerated.onForm({ section: "SkillInfo" }).iCheckField({ property: "ProposedForLearning" });
            Then.onThezlh_c_skillObjectPageGenerated.onForm({ section: "SkillInfo" }).iCheckField({ property: "Scale" });
            Then.onThezlh_c_skillObjectPageGenerated.onForm({ section: "SkillInfo" }).iCheckField({ property: "WantToLearn" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});