/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("zlh_c_skillListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onThezlh_c_skillListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onThezlh_c_skillListGenerated.onFilterBar().iCheckFilterField({ property: "Name" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onThezlh_c_skillListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onThezlh_c_skillListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onThezlh_c_skillListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onThezlh_c_skillListGenerated.onTable(defaultTableId).iCheckCreate({ visible: true });
            // When.onThezlh_c_skillListGenerated.onTable(defaultTableId).iPressCreate();
            // When.onThezlh_c_skillListGenerated.onTable(defaultTableId).iPressDelete();
            Then.onThezlh_c_skillListGenerated.onTable(defaultTableId).iCheckDelete({ visible: true });
            // When.onThezlh_c_skillListGenerated.onTable(defaultTableId).iPressAction("Suggest For");
            Then.onThezlh_c_skillListGenerated.onTable(defaultTableId).iCheckAction("Suggest For", { enabled: false });
            // When.onThezlh_c_skillListGenerated.onTable(defaultTableId).iPressAction("Want to Learn");
            Then.onThezlh_c_skillListGenerated.onTable(defaultTableId).iCheckAction("Want to Learn", { enabled: false });
            Then.onThezlh_c_skillListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"SkillId":{"header":"Skill"},"Name":{"header":"Name"},"Description":{"header":"Description"},"Category":{"header":"Category"},"AquiredByMe":{"header":"Acquired"},"ProposedForLearning":{"header":"Proposed for Learning"},"Scale":{"header":"Scale"},"WantToLearn":{"header":"Want to Learn"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onThezlh_c_skillListGenerated.onFilterBar().iExecuteSearch();
            Then.onThezlh_c_skillListGenerated.onTable(defaultTableId).iCheckRows();
            When.onThezlh_c_skillListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onThezlh_c_skillObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});