/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("zlh_c_courseObjectPageObjectPage journey");

        opaTest("Navigate to zlh_c_courseObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onThezlh_c_courseListGenerated.onFilterBar().iExecuteSearch();
            Then.onThezlh_c_courseListGenerated.onTable().iCheckRows();
            When.onThezlh_c_courseListGenerated.onTable().iPressRow(0);

            Then.onThezlh_c_courseObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            // Ensure the opened entity is not in Draft state before uncommenting
            // Then.onThezlh_c_courseObjectPageGenerated.onHeader().iCheckEdit({ visible: true });
            // When.onThezlh_c_courseObjectPageGenerated.onHeader().iPressEdit();
            Then.onThezlh_c_courseObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.zlh_personal_growth.v0001", action: "assignMeToCourse", unbound: false } /* , { enabled: true } */);
            // When.onThezlh_c_courseObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.zlh_personal_growth.v0001", action: "assignMeToCourse", unbound: false });
            Then.onThezlh_c_courseObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.zlh_personal_growth.v0001", action: "releaseCourse", unbound: false } /* , { enabled: true } */);
            // When.onThezlh_c_courseObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.zlh_personal_growth.v0001", action: "releaseCourse", unbound: false });
        });

        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onThezlh_c_courseObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "Header" });
            Then.onThezlh_c_courseObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header",
                field: "Type",
                targetAnnotation: ""
            });
            Then.onThezlh_c_courseObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header",
                field: "SkillCategory",
                targetAnnotation: ""
            });
            Then.onThezlh_c_courseObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header",
                field: "Name",
                targetAnnotation: ""
            });
            Then.onThezlh_c_courseObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header",
                field: "Released",
                targetAnnotation: ""
            });
            Then.onThezlh_c_courseObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Header",
                field: "Duration",
                targetAnnotation: ""
            });
            Then.onThezlh_c_courseObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "AvgRatingHeader" });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThezlh_c_courseObjectPageGenerated.iCheckNumberOfSections(2);
            When.onThezlh_c_courseObjectPageGenerated.iPressSectionIconTabFilterButton("Main");
            Then.onThezlh_c_courseObjectPageGenerated.iCheckSection({ section: "Main" });
            Then.onThezlh_c_courseObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "CourseId" });
            Then.onThezlh_c_courseObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "CourseKey" });
            Then.onThezlh_c_courseObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "Name" });
            Then.onThezlh_c_courseObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "Moderator" });
            Then.onThezlh_c_courseObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "Released" });
            Then.onThezlh_c_courseObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "Duration" });
            Then.onThezlh_c_courseObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "Type" });
            Then.onThezlh_c_courseObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "SkillCategory" });
            Then.onThezlh_c_courseObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "AverageRating" });
            When.onThezlh_c_courseObjectPageGenerated.iPressSectionIconTabFilterButton("MaterialsData");
            Then.onThezlh_c_courseObjectPageGenerated.iCheckSection({ section: "MaterialsData" });
            Then.onThezlh_c_courseObjectPageGenerated.onTable({ property: "_materials" }).iCheckColumns(undefined, {"Name":{"header":"Material Name"},"Duration":{"header":"Duration"},"Type":{"header":"Type"},"Content":{"header":"Content"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});