/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("zlh_c_materialObjectPageObjectPage journey");

        opaTest("Navigate to zlh_c_materialObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onThezlh_c_courseListGenerated.onFilterBar().iExecuteSearch();
            Then.onThezlh_c_courseListGenerated.onTable().iCheckRows();
            When.onThezlh_c_courseListGenerated.onTable().iPressRow(0);

            Then.onThezlh_c_courseObjectPageGenerated.iSeeThisPage();
            Then.onThezlh_c_courseObjectPageGenerated.onTable({ property: "_materials" }).iCheckRows();
            When.onThezlh_c_courseObjectPageGenerated.onTable({ property: "_materials" }).iPressRow(0);

            Then.onThezlh_c_materialObjectPageGenerated.iSeeThisPage();
        });


        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onThezlh_c_materialObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "Container" });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThezlh_c_materialObjectPageGenerated.iCheckSection({ section: "Main" });
            Then.onThezlh_c_materialObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "MaterialKey" });
            Then.onThezlh_c_materialObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "MaterialId" });
            Then.onThezlh_c_materialObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "CourseId" });
            Then.onThezlh_c_materialObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "Type" });
            Then.onThezlh_c_materialObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "Name" });
            Then.onThezlh_c_materialObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "Duration" });
            Then.onThezlh_c_materialObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "Content" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});